# Generated by Django 5.1.6 on 2025-08-14 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('chat_messages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together={('buyer', 'seller')},
        ),
        migrations.AddField(
            model_name='message',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='books.book'),
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='book',
        ),
    ]
